name: flutter_shader_fx_example
description: "A comprehensive example Flutter package providing pre-built, performance-optimized shader effects for Flutter's Impeller renderer. Create stunning GPU-accelerated visual effects without requiring shader programming knowledge."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.8.1
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_shader_fx:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-Light.ttf
          weight: 300
        - asset: fonts/Outfit-Regular.ttf
          weight: 400
        - asset: fonts/Outfit-Medium.ttf
          weight: 500
        - asset: fonts/Outfit-SemiBold.ttf
          weight: 600