name: flutter_shader_fx
description: "A comprehensive Flutter package providing pre-built, performance-optimized shader effects for Flutter's Impeller renderer. Create stunning GPU-accelerated visual effects without requiring shader programming knowledge."
version: 0.0.1
homepage: https://github.com/Tinalexman/flutter_shader_fx
repository: https://github.com/Tinalexman/flutter_shader_fx
issue_tracker: https://github.com/Tinalexman/flutter_shader_fx/issues

environment:
  sdk: ^3.8.1
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:

  shaders:
    - shaders/plasma.frag
  