name: flutter_shader_fx
description: "Pre-built, Impeller-optimized shader effects for Flutter. Add GPU-accelerated visuals with simple widgets—no GLSL required. (WIP: Plasma available)"
version: 0.0.1
homepage: https://github.com/Tinalexman/flutter_shader_fx
repository: https://github.com/Tinalexman/flutter_shader_fx
issue_tracker: https://github.com/Tinalexman/flutter_shader_fx/issues

environment:
  sdk: ^3.8.1
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:

  shaders:
    - shaders/plasma.frag
    - shaders/digital_glitch.frag
  